name: Lint CloudFormation Templates

on: [push]

jobs:
  cloudformation-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup cfn-lint action
        uses: scottbrenner/cfn-lint-action@v2

      - name: Print cfn-lint version
        run: |
          cfn-lint --version

      - name: Lint all template files
        run: |
          cfn-lint --info --debug --template templates/*.yml
